{% set version = "4.0.1" %}

package:
  name: libcifpp
  version: {{ version }}

source:
  url: https://github.com/PDB-REDO/libcifpp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0d3fc3f846a600275aab3b27ba2837b323dc758e7f314888d7c14d320d5c328a

test:
  commands:
    - test -e $PREFIX/include/cif++/Cif++.hpp

build:
  skip: True  # [osx]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - boost-cpp
    - cmake
    - make
    
about:
  home: https://github.com/PDB-REDO/libcifpp
  license: BSD-2
  license_file: LICENSE
  license_family: BSD
  summary: Library containing code to manipulate mmCIF and PDB files
  maintainers: multimeric
