{% set version="0.8.0" %}

package:
  name: quatradis
  version: {{ version }}

source:
  url: https://github.com/quadram-institute-bioscience/QuaTradis/archive/refs/tags/{{ version }}.tar.gz
  sha256: 21f47fc5abe2b9c6ce85a723886d37b90149f14843ce4dc6daa79b8ccd990820

build:
  number: 0
  noarch: python
  script: python -m pip install -v --no-deps --ignore-installed .

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - setuptools  # for pkg_resources
    - biopython
    - pysam
    - matplotlib-base
    - numpy
    - pandas
    - htslib
    - smalt
    - r-base
    - r-getopt
    - r-mass
    - bwa
    - minimap2
    - snakemake
    - snakeviz
        
test:
  commands:
    - tradis --help

about:
  home: https://github.com/quadram-institute-bioscience/QuaTradis
  license: 'GNU General Public License v3 (GPLv3)'
  license_family: GPL3
  license_file: LICENSE
  summary: 'A set of tools to analyse the output from TraDIS analyses'

extra:
  skip-lints:
    - uses_setuptools  # uses pkg_resources
  recipe-maintainers:
    - sbastkowski
    - maplesond
    - thanhleviet
  doi:
    - 10.1093/bioinformatics/btw022
