{% set name = "ngs-smap" %}
{% set version = "4.6.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 550f2ccad34b8d5abc8467924667ed58a833db8e493279eb9da1a5d70a985f9f
  patches:
    - patch

build:
  number: 0
  noarch: python
  entry_points:
    - smap = smap.__main__:main
  ignore_prefix_files: True
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - setuptools-scm
    - setuptools_scm_git_archive
    - python >=3.8.1
  run:
    - pybedtools~=0.9.0
    - pysam~=0.18.0
    - pandas~=1.4.0
    - matplotlib~=3.5.1
    - colorlog~=6.6.0
    - python >=3.8.1

test:
  commands:
    - smap compare --help

about:
  home: "https://gitlab.com/truttink/smap"
  license: "CC BY-NC-SA 4.0"
  license_family: CC
  license_file: 
  summary: "SMAP is an analysis tool for stack-based NGS read mapping"

extra:
  recipe-maintainers:
    - ieguinoa

