{% set version = "2.2.7" %}

package:
  name: secapr
  version: {{ version }}

source:
  url: https://github.com/AntonelliLab/seqcap_processor/archive/v{{ version }}.tar.gz
  sha256: 46684823d155f4817a953e65141c09b82682de92db4f8448411239b895ae0d1f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  entry_points:
    - secapr = secapr.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - pandas
    - matplotlib-base
    - biopython
    - trimmomatic
    - fastqc
    - abyss
    - spades
    - blast
    - mafft
    - muscle
    - emboss
    - bwa
    - samtools=1.9
    - trimal

test:
  imports:
    - secapr
  commands:
    - secapr --version

about:
  home: 'https://github.com/AntonelliLab/seqcap_processor'
  license: MIT
  license_file: LICENSE
  summary: 'Process sequence-capture FASTQ files into alignments for phylogenetic analyses. Integrates allele phasing.'
